import { AlertTriangle, CalendarDays, Package, ShieldAlert, TrendingUp } from 'lucide-react';
import { EmptyState, Notice, Pagination, Spinner, StatusBadge } from '../components/ui';
import { usePagedApi } from '../hooks/usePagedApi';

export default function RiskMonitorPage() {
  const state = usePagedApi('/dashboard/suspicious-products');
  const products = state.data.products ?? [];

  return <div className="min-h-screen bg-slate-50">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-6 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-red-600"><ShieldAlert className="size-4" /> Monitoring</p><h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Risk monitor</h1><p className="mt-2 text-sm text-slate-500">Products with unusually high confirmed verification activity.</p></div><span className="flex size-11 items-center justify-center rounded-xl bg-red-50 text-red-600"><AlertTriangle className="size-5" /></span></div></header>
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><Notice message={state.error} />
      {state.loading ? <div className="flex min-h-[300px] items-center justify-center rounded-2xl border border-slate-200 bg-white"><Spinner /></div> : products.length ? <div className="space-y-5">
        <section className="flex flex-col justify-between gap-4 rounded-2xl border border-red-100 bg-gradient-to-r from-red-50 to-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="flex items-start gap-4"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-red-100 text-red-600"><TrendingUp className="size-5" /></span><div><h2 className="font-semibold text-slate-900">Suspicious verification activity</h2><p className="mt-1 text-sm text-slate-500">Products are flagged when verified scans reach the configured threshold.</p></div></div><div className="rounded-xl border border-red-200 bg-white px-5 py-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Threshold</p><p className="mt-1 text-2xl font-bold text-red-600">{state.data.threshold}</p><p className="text-xs text-slate-500">verified scans / product</p></div></section>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4 sm:px-6"><span className="flex size-9 items-center justify-center rounded-lg bg-slate-100 text-slate-700"><Package className="size-4" /></span><div><h2 className="font-semibold text-slate-900">Products requiring attention</h2><p className="text-xs text-slate-500">{products.length} suspicious product{products.length === 1 ? '' : 's'} detected</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead className="bg-slate-50"><tr className="border-b border-slate-200">{['Product', 'SKU', 'Status', 'Verified scans', 'Last scan'].map((label) => <th className="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-slate-500" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{products.map((row) => <tr key={row.product.id} className="transition-colors hover:bg-slate-50"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-red-50 text-red-600"><Package className="size-5" /></span><p className="font-semibold text-slate-900">{row.product.name}</p></div></td><td className="px-6 py-4"><code className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-xs font-semibold text-slate-700">{row.product.sku}</code></td><td className="px-6 py-4"><StatusBadge value={row.product.status} /></td><td className="px-6 py-4"><span className="text-lg font-bold text-red-600">{row.verificationCount}</span><span className="ml-2 text-xs text-slate-400">scans</span></td><td className="px-6 py-4"><span className="flex items-center gap-2 text-sm text-slate-600"><CalendarDays className="size-4 text-slate-400" />{new Date(row.lastVerifiedAt).toLocaleString()}</span></td></tr>)}</tbody></table></div><div className="border-t border-slate-200 px-5 py-4 sm:px-6"><Pagination meta={state.meta} onChange={state.setPage} /></div></section>
      </div> : <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><EmptyState title="No products need attention" description="Products will appear here when their verified-scan volume reaches the configured threshold." /></div>}
    </div>
  </div>;
}
